apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-jznlleow
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-jznlleow:dcb04cb35b91803b21f96396b2804ef448fe16ad@sha256:45ce9260437fb2c8f680f1cc420834352a037ba892315042b5a3dfceca8cb339
          name: container-image
